apiVersion: v1
kind: Pod
metadata:
  name: compliant-pod-example
  namespace: smoke
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: app
      image: nginx:1.27
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
