sonar.projectKey=kubernetes-the-hard-way-vagrant-architect
sonar.projectName=Kubernetes The Hard Way - Architect Edition
sonar.projectVersion=V35

sonar.sources=scripts,ansible
sonar.language=sh,yaml
sonar.sourceEncoding=UTF-8
