[bastion]
bastion-0 ansible_host=192.168.56.9 role=bastion

[loadbalancer]
lb-0 ansible_host=192.168.56.10 role=lb

[identity]
keycloak-0 ansible_host=192.168.56.14 role=identity

[controllers]
controller-0 ansible_host=192.168.56.11 role=controller
controller-1 ansible_host=192.168.56.12 role=controller
controller-2 ansible_host=192.168.56.13 role=controller

[workers]
worker-0 ansible_host=192.168.56.21 role=worker pod_cidr=10.200.0.0/24
worker-1 ansible_host=192.168.56.22 role=worker pod_cidr=10.200.1.0/24
