Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  nodes = {
    "bastion-0"    => "192.168.56.9",
    "lb-0"         => "192.168.56.10",
    "keycloak-0"   => "192.168.56.14",
    "controller-0" => "192.168.56.11",
    "controller-1" => "192.168.56.12",
    "controller-2" => "192.168.56.13",
    "worker-0"     => "192.168.56.21",
    "worker-1"     => "192.168.56.22"
  }

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip

      if name == "bastion-0"
        node.vm.network "forwarded_port", guest: 22, host: 2222, auto_correct: true
      end

      if name == "keycloak-0"
        node.vm.network "forwarded_port", guest: 8443, host: 8443, auto_correct: true
        node.vm.network "forwarded_port", guest: 8080, host: 8081, auto_correct: true
      end

      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.memory = if name.start_with?("controller")
                      3072
                    elsif name == "keycloak-0"
                      3072
                    elsif name == "bastion-0"
                      1536
                    else
                      2048
                    end
        vb.cpus = 2
      end

      node.vm.provision "shell", path: "scripts/bootstrap-base.sh"
    end
  end
end
