[Service]
EnvironmentFile=-/etc/kubernetes/apiserver-oidc.env
ExecStart=
ExecStart=/usr/local/bin/kube-apiserver \
  --advertise-address=${INTERNAL_IP} \
  --allow-privileged=true \
  --apiserver-count=3 \
  --audit-log-path=/var/log/kubernetes/audit.log \
  --audit-policy-file=/etc/kubernetes/audit-policy.yaml \
  --authorization-mode=Node,RBAC \
  --client-ca-file=/etc/kubernetes/pki/ca.pem \
  --enable-admission-plugins=NodeRestriction,PodSecurity,ValidatingAdmissionPolicy \
  --enable-bootstrap-token-auth=true \
  --encryption-provider-config=/etc/kubernetes/encryption-config.yaml \
  --etcd-cafile=/etc/etcd/ca.pem \
  --etcd-certfile=/etc/etcd/kubernetes.pem \
  --etcd-keyfile=/etc/etcd/kubernetes-key.pem \
  --etcd-servers=https://192.168.56.11:2379,https://192.168.56.12:2379,https://192.168.56.13:2379 \
  --event-ttl=1h \
  --kubelet-certificate-authority=/etc/kubernetes/pki/ca.pem \
  --kubelet-client-certificate=/etc/kubernetes/pki/kubernetes.pem \
  --kubelet-client-key=/etc/kubernetes/pki/kubernetes-key.pem \
  --oidc-issuer-url=${OIDC_ISSUER_URL} \
  --oidc-client-id=${OIDC_CLIENT_ID} \
  --oidc-username-claim=${OIDC_USERNAME_CLAIM} \
  --oidc-groups-claim=${OIDC_GROUPS_CLAIM} \
  --oidc-ca-file=${OIDC_CA_FILE} \
  --oidc-username-prefix=${OIDC_USERNAME_PREFIX} \
  --oidc-groups-prefix=${OIDC_GROUPS_PREFIX} \
  --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.pem \
  --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client-key.pem \
  --requestheader-allowed-names=front-proxy-client \
  --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.pem \
  --requestheader-extra-headers-prefix=X-Remote-Extra- \
  --requestheader-group-headers=X-Remote-Group \
  --requestheader-username-headers=X-Remote-User \
  --secure-port=6443 \
  --service-account-issuer=https://kubernetes.default.svc.cluster.local \
  --service-account-key-file=/etc/kubernetes/pki/service-account.pem \
  --service-account-signing-key-file=/etc/kubernetes/pki/service-account-key.pem \
  --service-cluster-ip-range=10.32.0.0/24 \
  --tls-cert-file=/etc/kubernetes/pki/kubernetes.pem \
  --tls-private-key-file=/etc/kubernetes/pki/kubernetes-key.pem \
  --v=2
