apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-auditors-binding
subjects:
  - kind: Group
    name: k8s-platform-auditors
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: audit-reader
  apiGroup: rbac.authorization.k8s.io
