[bastion]
bastion-0 ansible_host=10.240.0.10 ansible_user=vagrant ansible_ssh_private_key_file=../../vagrant/.vagrant/machines/bastion-0/virtualbox/private_key

[loadbalancer]
lb-0 ansible_host=10.240.0.15 ansible_user=vagrant ansible_ssh_private_key_file=../../vagrant/.vagrant/machines/lb-0/virtualbox/private_key

[identity]
keycloak-0 ansible_host=10.240.0.16 ansible_user=vagrant ansible_ssh_private_key_file=../../vagrant/.vagrant/machines/keycloak-0/virtualbox/private_key

[controller]
controller-0 ansible_host=10.240.0.20 ansible_user=vagrant ansible_ssh_private_key_file=../../vagrant/.vagrant/machines/controller-0/virtualbox/private_key
controller-1 ansible_host=10.240.0.21 ansible_user=vagrant ansible_ssh_private_key_file=../../vagrant/.vagrant/machines/controller-1/virtualbox/private_key
controller-2 ansible_host=10.240.0.22 ansible_user=vagrant ansible_ssh_private_key_file=../../vagrant/.vagrant/machines/controller-2/virtualbox/private_key

[worker]
worker-0 ansible_host=10.240.0.30 ansible_user=vagrant ansible_ssh_private_key_file=../../vagrant/.vagrant/machines/worker-0/virtualbox/private_key
worker-1 ansible_host=10.240.0.31 ansible_user=vagrant ansible_ssh_private_key_file=../../vagrant/.vagrant/machines/worker-1/virtualbox/private_key

[kubernetes:children]
controller
worker

[all:vars]
ansible_python_interpreter=/usr/bin/python3
