apiVersion: v1
kind: Namespace
metadata:
  name: smoke
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-smoke
  namespace: smoke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-smoke
  template:
    metadata:
      labels:
        app: nginx-smoke
    spec:
      serviceAccountName: smoke-reader
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-smoke
  namespace: smoke
spec:
  selector:
    app: nginx-smoke
  ports:
    - port: 80
      targetPort: 80
